--
-- Add removed columns from the map table
--
ALTER TABLE map ADD COLUMN `score` BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE map ADD COLUMN `time` BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE map ADD COLUMN `times` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE map ADD COLUMN `kills` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE map ADD COLUMN `deaths` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE map ADD COLUMN `custom` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0;

--
-- Always delete record from version table!!!
--
DELETE FROM `_version` WHERE updateid = 30010;