FROM alpine:latest AS build
ARG TARGETPLATFORM
ARG BUILDPLATFORM
RUN echo "I am running on $BUILDPLATFORM, building for $TARGETPLATFORM"

# Set permissions for nginx's 'nginx' user
COPY ./src /src
WORKDIR /src
RUN chown -R 101:101 . \
    && find . -type d -exec chmod 750 {} \; \
    && find . -type f -exec chmod 640 {} \;

FROM nginx:1.21-alpine

# Add default configs
COPY config/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /src /src
