# This is a docker compose override file, for development builds with caching for CI environments
services:
  asp:
    build:
      cache_from:
        - type=local,src=/tmp/.buildx-cache-asp
      # cache_to:
      #   - type=local,dest=/tmp/.buildx-cache-asp,mode=maxmax
