version: '2.2'
services:
  init-container:
    image: alpine:latest
    volumes:
      - ./src:/src
      - db-volume:/var/lib/mysql
    entrypoint:
      - /bin/sh
    command:
      - -c
      - |
          set -eu

          echo "Granting db write permissions"
          chown -R 999:999 /var/lib/mysql

  asp:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    environment:
      # - XDEBUG_MODE=off   # Uncomment to disable xdebug
      # See ./src/ASP/system/config/config.php for all supported env vars
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=bf2stats
      - DB_USER=root
      - DB_PASS=ascent
    volumes:
      - ./src:/src
      - backups-volume:/src/ASP/system/backups # This volume is effectively unused since ASP doesn't allow DB backups for a remote DB, but mount it anyway to avoid errors.
      - cache-volume:/src/ASP/system/cache
      - config-volume:/src/ASP/system/config # For a stateful config file
      - logs-volume:/src/ASP/system/logs
      - snapshots-volume:/src/ASP/system/snapshots
    ports:
      - 8081:80
      - 9000
    networks:
      - bf2-network
    extra_hosts:
      # For xdebug to reach the host via `host.docker.internal`. See: https://github.com/moby/moby/pull/40007#issuecomment-578729356 and https://stackoverflow.com/questions/49907308/installing-xdebug-in-docker
      # If xdebug does not work, you may need to add an iptables rule to the INPUT chain: iptables -A INPUT -i br+ -j ACCEPT
      - host.docker.internal:host-gateway

  db:
    image: mariadb:10.8
    environment:
      - MARIADB_ROOT_PASSWORD=ascent
      # - MARIADB_USER=admin # Uncomment this if you want to create a regular user
      # - MARIADB_PASSWORD=admin # Uncomment this if you want to create a regular user
      - MARIADB_DATABASE=bf2stats
    volumes:
      - ./src/ASP/system/sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro # Seed the DB the first time
      - ./src/ASP/system/sql/data.sql:/docker-entrypoint-initdb.d/02-data.sql:ro # Seed the DB the first time
      - ./config/db/setup.sql:/docker-entrypoint-initdb.d/03-setup.sql:ro # Setup the DB the first time
      - ./config/db/my.cnf:/etc/my.cnf:ro
      - db-volume:/var/lib/mysql
    networks:
      - bf2-network
    depends_on:
      - init-container

  phpmyadmin:
    image: phpmyadmin:5.2
    environment:
      - PMA_HOST=db
    ports:
      - 8083:80
    networks:
      - bf2-network

networks:
  bf2-network:

volumes:
  backups-volume:
  cache-volume:
  config-volume:
  logs-volume:
  snapshots-volume:
  db-volume:
