# This is a docker compose override file, for production builds with caching for CI environments
services:
  bf2:
    image: startersclan/docker-bf2:v1.5.3153.0
    volumes:
      - ../../src/python:/server/bf2/python # Mount the python files

  asp:
    build:
      dockerfile: Dockerfile
      context: ../../
      target: prod
      cache_from:
        - type=local,src=/tmp/.buildx-cache-asp
      # cache_to:
      #   - type=local,dest=/tmp/.buildx-cache-asp,mode=max

  db:
    volumes:
      - ../../src/ASP/system/sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro # Seed the DB the first time
      - ../../src/ASP/system/sql/data.sql:/docker-entrypoint-initdb.d/02-data.sql:ro # Seed the DB the first time
      - ../../config/db/setup.sql:/docker-entrypoint-initdb.d/03-setup.sql:ro # Setup the DB the first time
