# This is a docker compose override file, for production builds with caching for CI environments
services:
  asp:
    build:
      dockerfile: Dockerfile
      context: ../../
      target: prod
      cache_from:
        - type=local,src=/tmp/.buildx-cache-asp
      # cache_to:
      #   - type=local,dest=/tmp/.buildx-cache-asp,mode=max
