--
-- Table structure for table `player_round_history`
--

CREATE TABLE `player_round_history` (
  `player_id` INT UNSIGNED NOT NULL,
  `round_id` INT UNSIGNED NOT NULL,
  `time` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `rank` TINYINT(2) UNSIGNED NOT NULL DEFAULT 0, -- Rank at the end of the round, post ASP corrections!
  `score` SMALLINT NOT NULL DEFAULT 0,
  `cmdscore` SMALLINT NOT NULL DEFAULT 0,
  `skillscore` SMALLINT NOT NULL DEFAULT 0,
  `teamscore` SMALLINT NOT NULL DEFAULT 0,
  `kills` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `deaths` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `captures` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `neutralizes` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `captureassists` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `neutralizeassists` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `defends` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `damageassists` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `heals` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `revives` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `ammos` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `repairs` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `targetassists` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `driverspecials` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `driverassists` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `passengerassists` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `teamkills` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `teamdamage` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `teamvehicledamage` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `suicides` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `killstreak` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `deathstreak` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `cmdtime` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `sqltime` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `sqmtime` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `lwtime` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `timepara` SMALLINT NOT NULL DEFAULT 0,	-- Time in parachute
  `completed` TINYINT(1) NOT NULL DEFAULT 0, -- Completed round?
  PRIMARY KEY(`player_id`, `round_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table `player_army_history`
--

CREATE TABLE `player_army_history` (
  `player_id` INT UNSIGNED NOT NULL,
  `round_id` INT UNSIGNED NOT NULL,
  `army_id` TINYINT UNSIGNED NOT NULL,
  `time` MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  `score` SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY(`player_id`,`round_id`,`army_id`),
  FOREIGN KEY(`player_id`) REFERENCES player(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(`round_id`) REFERENCES round(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(`army_id`) REFERENCES army(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table `player_kit_history`
--

CREATE TABLE `player_kit_history` (
  `player_id` INT UNSIGNED NOT NULL,
  `round_id` INT UNSIGNED NOT NULL,
  `kit_id` SMALLINT UNSIGNED NOT NULL,
  `time` MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  `kills` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `deaths` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY(`player_id`,`round_id`,`kit_id`),
  FOREIGN KEY(`player_id`) REFERENCES player(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(`round_id`) REFERENCES round(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(`kit_id`) REFERENCES kit(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table `player_kit_history`
--

CREATE TABLE `player_kill_history` (
  `round_id` INT UNSIGNED NOT NULL,
  `attacker` INT UNSIGNED NOT NULL,
  `victim` INT UNSIGNED NOT NULL,
  `count` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY(`attacker`,`round_id`,`victim`),
  FOREIGN KEY(`attacker`) REFERENCES player(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(`round_id`) REFERENCES round(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(`victim`) REFERENCES player(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table `player_vehicle_history`
--

CREATE TABLE `player_vehicle_history` (
  `player_id` INT UNSIGNED NOT NULL,
  `round_id` INT UNSIGNED NOT NULL,
  `vehicle_id` TINYINT UNSIGNED NOT NULL,
  `time` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `kills` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `deaths` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `roadkills` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY(`player_id`,`round_id`,`vehicle_id`),
  FOREIGN KEY(`player_id`) REFERENCES player(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(`round_id`) REFERENCES round(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(`vehicle_id`) REFERENCES vehicle(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table `weapons_history`
--

CREATE TABLE `player_weapon_history` (
  `player_id` INT UNSIGNED NOT NULL,
  `round_id` INT UNSIGNED NOT NULL,
  `weapon_id` TINYINT UNSIGNED NOT NULL,
  `time` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `kills` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `deaths` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `fired` MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  `hits` MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY(`player_id`,`round_id`,`weapon_id`),
  FOREIGN KEY(`player_id`) REFERENCES player(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(`round_id`) REFERENCES round(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(`weapon_id`) REFERENCES weapon(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;